
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MobCA
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create